config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'feedback' => 'static_pages#feedback'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      patch 'follow_top_sites'
    end
  end
  resources :feeds
  resources :opml, only: [:new, :create]
  resources :password_resets
  resources :sessions
  resources :subscriptions
  resources :payments
  get 'opml/export' => 'opml#export'
  get 'next' => 'subscriptions#next'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?
    cookies[:check_for_updated_subs] = true
    redirect_to current_user.next_feed
  end

  def feedback
    redirect_to root_url unless logged_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/feedback.html.erb
<% provide(:title, "Feedback") %>

<div class="row simple-container">
    <div class="small-11 medium-7 small-centered columns box">
	<header>
	    <h3>Feedback</h3>
	</header>

	<p>You can send any suggestions, questions and bug reports by the following means:</p>

	<p><strong>Email:</strong> <%= mail_to 'thiago@fastmail.com', nil, target: '_blank' %></p>
	<p><strong>GitHub:</strong> <%= link_to 'trsantos/sourcerer', 'https://github.com/trsantos/sourcerer', target: '_blank' %></p>
    </div>
</div>

app/views/static_pages/home.html.erb
<div id="homepage">
    <section id="top">
	<header>
	    <div class="row">
		<div class="columns">
		    <%= image_tag 'logo_white.png', id: 'logo', class: 'float-left' %>
		    <%= link_to "Log in", login_path, id: 'login-button', class: "button hollow float-right radius" %>
		</div>
	    </div>
	</header>
	<div class="row">
	    <div class="columns">
		<h1 class="tagline text-center">The sorcerer of news sources</h1>
	    </div>
	</div>
	<div class="row">
	    <div class="medium-5 medium-centered large-4 columns">
		<%= link_to "Get started for free", signup_path, class: "button large expanded radius" %>
	    </div>
	</div>
    </section>

    <section id="screenshot">
	<div class="row">
	    <div class="columns">
		<picture class="float-center">
		    <source srcset="<%= image_path 'ss-large.png' %>" media="(min-width: 64em)">
		    <source srcset="<%= image_path 'ss-medium.png' %>" media="(min-width: 40em)">
		    <source srcset="<%= image_path 'ss-small.png' %>">
		    <img src="<%= image_path 'ss-large.png' %>">
		</picture>
	    </div>
	</div>
    </section>

    <section class="main-features">
	<div class="row small-up-1 medium-up-2">
	    <div class="column">
		<%= icon 'fas', 'newspaper' %>
		<p>Follow your favorite websites, blogs, comics and more. Subscribe to anything with an RSS feed.</p>
	    </div>
	    <div class="column">
		<%= icon 'fas', 'magic' %>
		<p>Get news from all your sources, no exceptions. High volume feeds will not appear too often.</p>
	    </div>
	    <div class="column">
		<%= icon 'fas', 'star' %>
		<p>Star your must-read sources. These will be shown before anything else, whenever updated.</p>
	    </div>
	    <div class="column">
		<%= icon 'fas', 'desktop' %>
		<%= icon 'fas', 'tablet' %>
		<%= icon 'fas', 'mobile' %>
		<p>Read on the go. Sourcerer works on all your devices. No app to install, just visit the website.</p>
	    </div>
	</div>
    </section>

    <section id="pricing">
	<div class="row text-center">
	    <div class="column">
		<header>
		    <h4>Pricing</h2>
		</header>
		<ul class="no-bullet">
		    <li><strong>Free:</strong> follow up to <%= Payment.feed_limit %> feeds.</li>
		    <li><strong>$<%= Payment.price %> / year:</strong> unlimited feeds, pay after <%= Payment.trial_duration.to_i/60/60/24 %>-day trial.</li>
		</ul>
	    </div>
	</div>
    </section>

    <footer>
	<div class="row text-center">
	    <div class="column">
		<p>Sourcerer is a Free and Open Source Software created by Thiago Rodrigues.</p>
		<%= mail_to 'thiago@fastmail.com', icon('envelope-o', 'Email', style: 'margin-right: 1px'), target: '_blank', style: 'margin-right: 15px' %>
		<%= link_to icon('github', 'GitHub'), 'https://github.com/trsantos/sourcerer', target: '_blank' %>
	    </div>
	</div>
    </footer>
</div>