config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'feedback' => 'static_pages#feedback'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      patch 'follow_top_sites'
    end
  end
  resources :feeds
  resources :opml, only: [:new, :create]
  resources :password_resets
  resources :sessions
  resources :subscriptions
  resources :payments
  get 'opml/export' => 'opml#export'
  get 'next' => 'subscriptions#next'
end

app/models/feed.rb
class Feed < ApplicationRecord
  include ActionView::Helpers::SanitizeHelper
  include ApplicationHelper

  has_many :subscriptions, dependent: :delete_all
  has_many :users, through: :subscriptions
  has_many :entries, dependent: :delete_all

  validates :feed_url, presence: true, uniqueness: true
  after_create :delayed_update

  def self.entries_per_feed
    10
  end

  def self.update_all_feeds
    Feed.find_each do |f|
      FeedUpdateJob.perform_later f
    end
  end

  def update
    fj_feed = fetch_and_parse
    return if fj_feed.is_a? Integer
    transaction do
      update_entries fj_feed
      update_feed_attributes fj_feed
    end
  end

  def only_images?
    entries.each do |e|
      return false unless e.image && (strip_tags e.description).blank?
    end
    true
  end

  private

  def fetch_and_parse
    setup_fj
    Feedjira::Feed.fetch_and_parse feed_url
  rescue
    update_attribute :fetching, false
    0
  end

  def update_feed_attributes(fj_feed)
    update_attributes(title: fj_feed.title,
                      site_url: process_url(fj_feed.url),
                      description: find_feed_description(fj_feed),
                      logo: check_feed_logo(fj_feed.logo),
                      has_only_images: only_images?,
                      fetching: false,
                      updated_at: Time.current)
  end

  def find_feed_description(fj_feed)
    fj_feed.description
  rescue
    nil
  end

  def check_feed_logo(logo)
    return if logo.nil?
    if (logo.include? 'wp.com/i/buttonw-com') ||
       (logo.include? 'creativecommons.org/images/public')
      nil
    else
      logo
    end
  end

  def update_entries(fj_feed)
    old_entries_count = entries.count
    fj_feed.entries.first(Feed.entries_per_feed).reverse_each do |fj_entry|
      insert_or_update_entry fj_entry
    end
    return unless entries.count > old_entries_count
    discard_old_entries
    mark_subscriptions_as_updated
  end

  def discard_old_entries
    self.entries = entries.order(updated_at: :desc).first(Feed.entries_per_feed)
  end

  def mark_subscriptions_as_updated
    subscriptions.where(updated: false).update_all(updated: true)
  end

  def insert_or_update_entry(fj_entry)
    entries.find_by(url: fj_entry.url).touch
  rescue
    insert_entry fj_entry
  end

  def insert_entry(e)
    description = e.content || e.summary || ''
    entries.create(title:       (e.title unless e.title.blank?),
                   description: description,
                   pub_date:    find_date(e.published),
                   image:       find_image(e, description),
                   url:         e.url)
  end

  def setup_fj
    Feedjira::Feed
      .add_common_feed_entry_element(:enclosure, value: :url, as: :image)
    Feedjira::Feed
      .add_common_feed_entry_element('media:thumbnail', value: :url, as: :image)
    Feedjira::Feed
      .add_common_feed_entry_element('media:content', value: :url, as: :image)

    Feedjira::Feed.add_common_feed_element(:url, as: :logo, ancestor: :image)
    Feedjira::Feed.add_common_feed_element(:logo, as: :logo)
  end

  def find_date(pub_date)
    return Time.current if pub_date.nil? || pub_date > Time.current
    pub_date
  end

  def find_image(entry, desc)
    process_image entry.image || image_from_description(desc)
  end

  def process_image(img)
    return if bad_image?(img)
    hacks parse_image img
  end

  def parse_image(img)
    # Need to add http here as some images won't
    # load because ssl_error_bad_cert_domain
    return 'http:' + img if img.start_with?('//')
    uri = URI.parse feed_url
    start = uri.scheme + '://' + uri.host
    return start + img if img.start_with? '/'
    # I don't remeber why this is here. Maybe not needed?
    return start + uri.path + img unless img.start_with? 'http'
    img
  end

  def image_from_description(description)
    doc = Nokogiri::HTML description
    doc.css('img').first.attributes['src'].value
  rescue
    nil
  end

  def hacks(img)
    if img.include? 'wordpress.com'
      img.sub!(/\?.*/, '')
      img += '?w=800'
    elsif (img.include? 'img.youtube.com') || (img.include? 'i.ytimg.com')
      img.sub! '/default', '/hqdefault'
    elsif (img.include? 'googleusercontent.com') ||
          (img.include? 'blogspot.com')
      img.sub! 's72-c', 's640'
    end
    img
  end

  def bad_image?(img)
    img.nil? ||
      (img.include? 'feedburner.com') ||
      (img.include? 'feedsportal.com') ||
      (img.include? '/comments/') # Wordpress
  end

  def delayed_update
    FeedUpdateJob.set(queue: :critical).perform_later(self)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  include ApplicationHelper

  before_action :logged_in_user
  before_action :set_user
  before_action :check_expiration_date
  before_action :set_subscription, only: [:show]
  before_action :unread_feeds, only: [:show]

  def show
    cookies.delete :check_for_updated_subs
    @feed = Feed.find(params[:id])
    @entries = @feed.entries.order(pub_date: :desc) unless @feed.fetching
  end

  def new
    return unless params[:feed]
    feed = Feed.find_or_create_by(feed_url: process_url(params[:feed]))
    redirect_to feed
  end

  def create
    url = params[:feed][:feed_url]
    feed = Feed.find_or_create_by(feed_url: process_url(url))
    redirect_to feed
  end

  private

  def set_user
    @user = current_user
    @user.touch
  end

  def check_expiration_date
    return unless @user.feeds.count > Payment.feed_limit &&
                  Time.current > @user.expiration_date
    redirect_to new_payment_path
  end

  def set_subscription
    @subscription = @user.subscriptions.find_by(feed_id: params[:id])
  end

  def unread_feeds
    return unless @subscription
    return unless cookies[:check_for_updated_subs]
    return if @user.subscriptions.exists?(updated: true)
    flash.now[:primary] =
      'You have no updated feeds right now. Check back later!'
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def sub_title(feed)
    if @subscription
      @subscription.title || feed.title
    else
      feed.title
    end
  end
  
  

  def sub_url(feed)
    if @subscription
      @subscription.site_url || feed.site_url
    else
      feed.site_url
    end
  end

  def favicon_for(url)
    uri = URI.parse url
    uri.scheme + '://' + uri.host + '/favicon.ico'
  rescue
    image_path 'feed-icon.png'
  end

  def show_payment_aside?
    @user.feeds.count > Payment.feed_limit &&
      Time.current > @user.expiration_date - Payment.trial_duration
  end
end

app/views/feeds/_aside.html.erb
<aside class="show-for-large">
    <div class="large-3 columns">
	<section id="info">
	    <p class="section-heading">Feed info</p>
	    <% if @feed.logo %>
		<div id="feed-logo">
		    <%= image_tag @feed.logo, id: 'logo-img' %>
		</div>
	    <% end %>
	    <% if @feed.description %>
		<p id="aside-description"><%= sanitize @feed.description %></p>
	    <% else %>
		<p id="aside-title"><%= sub_title @feed %></p>
	    <% end %>
	    <div id="resources">
		<strong>
		    <%= link_to "Website", sub_url(@feed), target: "_blank" %><br/>
		    <%= link_to "Raw feed", @feed.feed_url, target: "_blank" %>
		</strong>
	    </div>
	</section>
	<% if show_payment_aside? %>
	    <section id="payment">
		<div class="aside-sep"></div>
		<p class="section-heading">Important</p>
		<div id="aside-sub">
		    <p>Your subscription is about to end.</p>
		    <strong><%= link_to 'Renew it now', new_payment_path %></strong>
		</div>
	    </section>
	<% end %>
    </div>
</aside>

<script>
 var logo = document.getElementById("logo-img");
 if (logo) {
     logo.onerror = function() {
	 logo.style.display = "none";
     };
     logo.onload = function() {
	 if (logo.width < 20) {
	     logo.style.display = "none";
	 }
     }
 }
</script>

app/views/feeds/_controls.html.erb
<ul id="feed-controls" class="menu vertical medium-horizontal" data-responsive-menu="drilldown medium-dropdown">
    <% if @subscription %>
	<% if @subscription.starred %>
	    <li>
		<%= link_to "Unstar",
		subscription_path(@subscription, subscription: { starred: false }),
		remote: true,
		method: :patch %>
	    </li>
	<% else %>
	    <li>
		<%= link_to "Star",
		subscription_path(@subscription, subscription: { starred: true }),
		remote: true,
		method: :patch,
		title: "Starred feeds will be displayed first when updated. This is for your must-reads." %>
	    </li>
	<% end %>
	<li>
	    <%= link_to "Edit", edit_subscription_path(@subscription) %>
	</li>
	<li>
	    <%= link_to "Unsubscribe",
	    subscription_path(@subscription),
	    remote: true,
	    method: :delete %>
	</li>
    <% else %>
	<li>
	    <%= link_to "Subscribe",
	    subscriptions_path(feed_id: @feed.id),
	    remote: true,
	    method: :post %>
	</li>
    <% end %>
    <li class="show-for-medium">
	<%= link_to 'Next feed', next_path(last_sub: @subscription), class: 'button', accesskey: 'n' %>
    </li>
    <li class="show-for-small-only">
	<%= link_to current_user.name.split.first, '#' %>
	<ul class="menu vertical">
	    <% if current_user.subscriptions.any? %>
		<li><%= link_to "Subscriptions", subscriptions_path %></li>
	    <% end %>
	    <li><%= link_to "Setup", current_user %></li>
	    <li><%= link_to "Account", edit_user_path(current_user) %></li>
	    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
	</ul>
    </li>
</ul>

app/views/feeds/new.html.erb
<% provide(:title, "New feed") %>

<div class="row simple-container">
    <div class="small-11 medium-7 small-centered columns box">
	<header>
	    <h3>New feed</h3>
	</header>

	<%= form_for(Feed.new) do |f| %>
	    <%= f.label :feed %>
	    <%= f.text_field :feed_url, placeholder: 'Paste a feed URL here', autofocus: true %>
	    <%= f.submit "Submit", class: "button radius expanded", data: { disable_with: "Please wait..." } %>
	<% end %>

	<section class="tips">
	    <p><%= icon 'fab', 'wikipedia-w', class: 'fa-fw' %><em> Take a look at Wikipedia's article about <%= link_to 'Web Feeds', 'https://en.wikipedia.org/wiki/Web_feed', target: '_blank' %>.</em></p>
	    <% if browser.firefox? %>
		<p><%= icon 'fab', 'firefox', class: 'fa-fw' %><em> <%= link_to 'Add Sourcerer', '#', id: 'firefox' %> as a Feed Reader for Firefox.</em></p>
		<script>
		 var ff = document.getElementById("firefox");
		 ff.onclick = function () {
		     navigator.registerContentHandler("application/vnd.mozilla.maybe.feed", "<%= "#{request.protocol}#{request.host_with_port}" %>/feeds/new?feed=%s", "Sourcerer");
		 };
		</script>
	    <% end %>
	</section>
    </div>
</div>

app/views/feeds/show.html.erb
<% provide(:title, @feed.title) %>

<div id="feeds-show-container" class="row">
    <%= render 'aside' %>
    <div class="large-9 large-uncentered columns end box">
	<% if @feed.fetching %>
	    <p style="margin-top: 1.25rem"><%= icon 'fas', 'sync', class: 'fa-spin', style: 'margin-right: 5px' %> Please wait...</p>
            <script>
             window.setTimeout(() => { Turbolinks.visit(); }, 1000);
            </script>
	<% else %>
	    <% if @feed.entries.any? %>
		<p id="whats-new" class="show-for-large section-heading">What's new</p>
		<%= render @entries %>
	    <% else %>
		<p style="margin-top: 1.25rem">There are no articles for this feed.</p>
	    <% end %>
	<% end %>
    </div>
</div>

<%= link_to 'Next feed', next_path(last_sub: @subscription), class: 'show-for-small-only button expanded', id: 'next' %>