config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'feedback' => 'static_pages#feedback'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      patch 'follow_top_sites'
    end
  end
  resources :feeds
  resources :opml, only: [:new, :create]
  resources :password_resets
  resources :sessions
  resources :subscriptions
  resources :payments
  get 'opml/export' => 'opml#export'
  get 'next' => 'subscriptions#next'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :subscriptions, dependent: :delete_all
  has_many :feeds, through: :subscriptions
  has_many :entries, through: :feeds
  has_many :payments

  before_create { generate_token(:auth_token) }
  before_create :set_expiration_date
  before_save :downcase_email

  validates :name,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,
            presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_blank: true

  def generate_token(column)
    loop do
      self[column] = SecureRandom.urlsafe_base64
      break unless User.exists?(column => self[column])
    end
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.current
    save!
    UserMailer.password_reset(self).deliver_later(queue: :default)
  end

  def unfollow(feed)
    s = subscriptions.find_by(feed_id: feed.id)
    s.destroy if s
  end

  def following?(feed)
    feeds.include?(feed)
  end

  def next_feed
    if subscriptions.any?
      sub = updated_sub || random_sub
      sub.feed
    else
      self
    end
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.strip.downcase
  end

  def set_expiration_date
    self.expiration_date = Payment.trial_duration.from_now
  end

  def updated_sub
    subscriptions
      .where(updated: true)
      .order(starred: :desc, visited_at: :asc).first
  end

  def random_sub
    subscriptions.order('RANDOM()').take
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user,   only: [:show, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash.now[:success] = 'Profile updated.'
    end
    render 'edit'
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:primary] = 'User deleted succesfully.'
    redirect_to root_url
  end

  def follow_top_sites
    user = current_user
    Feed.where(top_site: true).shuffle.each do |f|
      user.subscriptions.find_or_create_by(feed: f)
    end
    flash[:primary] = 'Ok, done! Happy reading.'
    redirect_to user.next_feed
  end

  private

  def user_params
    params
      .require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user == @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

app/views/users/edit.html.erb
<% provide(:title, "Account") %>

<div class="row simple-container">
    <div class="small-11 medium-7 small-centered columns box">
	<header>
	    <h3>Your account</h3>
	</header>

	<%= form_for(@user) do |f| %>
	    <%= render 'shared/error_messages' %>

	    <%= f.label :name %>
	    <%= f.text_field :name %>

	    <%= f.label :email %>
	    <%= f.email_field :email %>

	    <%= f.submit "Save changes", class: "button radius expanded", data: { disable_with: "Please wait..." } %>
	<% end %>
	<p data-no-turbolink>
	    <strong>Subscription end date:</strong> <%= @user.expiration_date.to_date.to_formatted_s(:long) %><br>
	    <%= link_to "Export your data", opml_export_path %><br>
	    <%= link_to "Delete your account", current_user, method: :delete, data: { confirm: "Are you sure you want to delete your account? This can't be undone." } %>
	</p>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="logo-wrap">
    <%= link_to image_tag('logo_white.png'), root_url %>
</div>

<div class="row simple-container">
    <div class="small-11 medium-5 columns small-centered box auth-box">
	<header>
	    <h3>Create your account</h3>
	</header>

	<%= form_for(@user) do |f| %>
	    <%= render 'fields', f: f %>
	    <%= f.submit "Sign up", class: "button radius expanded", data: { disable_with: "Please wait..." } %>
	<% end %>

	<p class="text-center">Already use Sourcerer? <%= link_to 'Log in', login_path %></p>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row simple-container">
    <div class="small-11 medium-7 small-centered columns box">
	<header>
	    <h3>Hello, <%= @user.name.split.first %></h3>
	</header>

	<p>If this is your first time with a feed reader, you can begin by following a list of popular sites:</p>

	<%= form_for :user, url: follow_top_sites_user_path, method: 'patch' do |f| %>
	    <%= f.submit 'Follow popular websites', class: 'button radius expanded', data: { disable_with: 'Please wait...' } %>
	<% end %>

	<p>Otherwise, you can import your own feed list:</p>

	<%= link_to 'Import OPML file', new_opml_path, class: 'button secondary radius expanded' %>
    </div>
</div>