config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'feedback' => 'static_pages#feedback'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      patch 'follow_top_sites'
    end
  end
  resources :feeds
  resources :opml, only: [:new, :create]
  resources :password_resets
  resources :sessions
  resources :subscriptions
  resources :payments
  get 'opml/export' => 'opml#export'
  get 'next' => 'subscriptions#next'
end

app/views/layouts/_nav.html.erb
<div class="top-bar fixed">
    <div class="row <%= 'hide-for-small-only' if in_feeds_show %>">
	<div class="top-bar-title">
	    <span class="float-right" data-responsive-toggle="responsive-menu-1" data-hide-for="medium">
		<span class="menu-icon" data-toggle></span>
	    </span>
	    <%= link_to image_tag('logo_nav.png'), root_url, id: 'logo' %>
	</div>
	<div id="responsive-menu-1">
	    <div class="top-bar-right">
		<ul class="vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown" data-disable-hover="true" data-click-open="true">
		    <li class="show-for-small-only"><%= link_to "Back to reading", root_url %></li>
		    <li><%= link_to "New feed", new_feed_path %></li>
		    <% if current_user.subscriptions.any? %>
			<li><%= link_to "Subscriptions", subscriptions_path %></li>
		    <% end %>
		    <li>
			<%= link_to current_user.name.split.first, '#' %>
			<ul class="vertical menu">
			    <li><%= link_to "Setup", current_user %></li>
			    <li><%= link_to "Feedback", feedback_path %></li>
			    <li><%= link_to "Account", edit_user_path(current_user) %></li>
			    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
			</ul>
		    </li>
		</ul>
	    </div>
	</div>
    </div>
    <% if in_feeds_show %>
	<div id="feed-header">
	    <div class="row">
		<div class="top-bar-title">
		    <span class="float-right" data-responsive-toggle="responsive-menu-2" data-hide-for="medium">
			<span class="menu-icon" data-toggle></span>
		    </span>
		    <% unless @feed.fetching %>
			<a href="<%= sub_url(@feed) %>" id="feed-title" target="_blank">
			    <img id="favicon" src="<%= favicon_for(sub_url(@feed)) %>"/>
			    <%= sub_title(@feed) %>
			</a>
		    <% end %>
		</div>
		<div id="responsive-menu-2">
		    <div class="top-bar-right">
			<%= render 'feeds/controls' %>
		    </div>
		</div>
	    </div>
	</div>
    <% end %>
</div>

<div id="main-nav-padding"></div>

<% if in_feeds_show %>
    <div id="feed-nav-padding" class="show-for-medium"></div>

    <script>
     var favicon = document.getElementById("favicon");
     favicon.onerror = function() {
	 favicon.setAttribute("src", "<%= image_path 'feed-icon.png' %>");
     }
    </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag %>
    </head>
    <body class="<%= 'dark-page' unless logged_in? %>">
	<% if logged_in? %>
	    <%= render 'layouts/nav' %>
	<% end %>
	<% flash.each do |message_type, message| %>
	    <div class="text-center callout <%= message_type %>">
		<%= message %>
	    </div>
	<% end %>
	<%= yield %>
    </body>
</html>